### ISSUE TITLE
Compare to Terminus Build Tools plugin

### ISSUE THREAD

**Issue by greg-1-anderson** [FloeDesignTechnologies/terminus-pushcode#1]
https://github.com/pantheon-systems/terminus-build-tools-plugin

I only see one thing that I do differently, offhand: I use `--force` with `git add`, and ignore all of the build results in .gitignore.

I should use Robo tasks in my tool, as you do here.

**Comment by pbuyle** [comment]
If I understand correctly, the corresponding command in Terminus Build Tools, would be `build-env:create`.

The difference is that this plugin/command:

- Does not require the current directory to be a Git (or any other VCS) repository. As a result, if the current working directory is a Git repository, it is kept completely separated from the one on Pantheon.
- Does not enforce/manage environments
- Provide a simple and well-known mechanism to ignore files that should be kept in the current working directory but not pushed to Pantheon

In this way, the command does not enforce/expect any particular development workflow. My hope is that it would be suitable for a large variety of different workflows.

**Comment by pbuyle** [comment]
While VCS/SCM independence is a goal, the current implementation still require the current working directory to be a Git repository (see #3)

**Comment by greg-1-anderson** [comment]
Sounds good. Thanks for sharing your tool.
