### ISSUE TITLE
What prevents this command from inadvertently wiping out an existing Pantheon environment?

### ISSUE THREAD

**Issue by uberhacker** [FloeDesignTechnologies/terminus-pushcode#2]
@pbuyle: I really like the way you are performing validation on the input parameters but unless I'm missing it, shouldn't the current environment on the Pantheon side be backed up first just in case the user accidentally overwrites something they want to keep?

Maybe you could add another option called `--backup` and default it to true with the option to override to speed things up on deployments?

**Comment by pbuyle** [comment]
Because the command push the code to Pantheon as a new Git commit without rewriting history, the Git repository on Pantheon is your backup.
